name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Compile
        run: |
          javac Main.java

      # Run the app and immediately choose "4" (Exit) so it doesn't block CI
      - name: Smoke run (auto-exit)
        run: |
          printf "4\n" | java Main
